services:
  - type: web
    name: gold-saas-bp
    env: ruby
    buildCommand: "" # 👈 disables default precompile!
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
